# Maximum width of each line
max_width = 120

# Use spaces for indentation
tab_spaces = 4

# Use spaces for indentation
use_small_heuristics = "Max"

# Format code in edition 2021
edition = "2021"

# Format string literals where necessary
format_strings = true

# Format comments
format_code_in_doc_comments = true

# Group imports
group_imports = "StdExternalCrate"

# Sort imports
imports_granularity = "Module"

# Merge multiple imports
merge_derives = true

# Use Unix-style newlines
newline_style = "Unix"

# Use trailing commas in multiline
trailing_comma = "Vertical"

# Use trailing commas in multiline
trailing_semicolon = true

# Use trailing commas in multiline
trailing_single_line = true

# Use trailing commas in multiline
use_field_init_shorthand = true

# Use trailing commas in multiline
use_try_shorthand = true 